
@node SQL Data Types
@appendix SQL Data Types

As Firebird's documentation is lacking on which specific types match up to which SQL types, a convenient mapping of SQL types to Nim is provided:

@multitable {SQL_TIMESTAMP} {Memory buffer}
@headitem Type name
@tab Nim type
@item SQL_TEXT
@tab string@footnote{TODO document special use of strings here.}
@item SQL_VARYING
@tab string@footnote{TODO document use of special struct for this.}
@item SQL_SHORT
@tab cshort
@item SQL_LONG
@tab clong
@item SQL_FLOAT
@tab cfloat
@item SQL_DOUBLE
@tab cdouble
@item SQL_D_FLOAT
@tab ???
@item SQL_TIMESTAMP
@tab TIMESTAMP
@item SQL_DATE@footnote{Date is a synonym for Timestamp.}
@tab TIMESTAMP
@item SQL_BLOB@footnote{Blob has multiple sub-types, see @ref{blob subtypes}@.}
@tab GDS_QUAD
@item SQL_ARRAY
@tab GDS_QUAD
@item SQL_QUAD
@tab GDS_QUAD
@item SQL_TYPE_TIME
@tab TIME
@item SQL_TYPE_DATE
@tab DATE
@item SQL_INT64
@tab int64
@item SQL_BOOLEAN
@tab ???
@item SQL_NULL
@tab ???
@end multitable

@cite{Firebird 3.0's example/api/apifull.c file}
